export default {
  // check server
  CHECK_SERVER: 'CHECK_SERVER',
  CHECK_SERVER_START: 'CHECK_SERVER_START',
  CHECK_SERVER_SUCCESS: 'CHECK_SERVER_SUCCESS',
  CHECK_SERVER_ERROR: 'CHECK_SERVER_ERROR',
  CHECK_SERVER_FINISH: 'CHECK_SERVER_FINISH',

  // checking existed user (token from LS)
  START_CHECK_EXISTED_USER: 'START_CHECK_EXISTED_USER',
  FINISH_CHECK_EXISTED_USER: 'FINISH_CHECK_EXISTED_USER',

  // active tab for sidebar
  CHANGE_ACTIVE_TAB: 'CHANGE_ACTIVE_TAB',

  // user
  USER_LOAD: 'USER_LOAD',
  USER_LOAD_START: 'USER_LOAD_START',
  USER_LOAD_SUCCESS: 'USER_LOAD_SUCCESS',
  USER_LOAD_ERROR: 'USER_LOAD_ERROR',
  USER_LOAD_FINISH: 'USER_LOAD_FINISH',

  // io
  IO_CONNECT: 'IO_CONNECT',
  APP_AUTHENTICATED: 'APP_AUTHENTICATED',

  // logOut
  LOG_OUT: 'LOG_OUT',
  FORCE_LOGOUT: 'FORCE_LOGOUT',

  // wallets
  WALLET_LIST: 'WALLET_LIST',
  WALLET_LIST_START: 'WALLET_LIST_START',
  WALLET_LIST_SUCCESS: 'WALLET_LIST_SUCCESS',
  WALLET_LIST_ERROR: 'WALLET_LIST_ERROR',
  WALLET_LIST_FINISH: 'WALLET_LIST_FINISH',

  // generation & activation
  WALLET_NEW_PREPARE: 'WALLET_NEW_PREPARE',
  WALLET_NEW_CHANGE_NAME: 'WALLET_NEW_CHANGE_NAME',
  WALLET_NEW_CHANGE_TYPE: 'WALLET_NEW_CHANGE_TYPE',
  WALLET_IMPORT_CHANGE_TYPE: 'WALLET_IMPORT_CHANGE_TYPE',

  WALLET_NEW_GENERATION: 'WALLET_NEW_GENERATION',
  WALLET_NEW_GENERATION_START: 'WALLET_NEW_GENERATION_START',
  WALLET_NEW_GENERATION_SUCCESS: 'WALLET_NEW_GENERATION_SUCCESS',
  WALLET_NEW_GENERATION_ERROR: 'WALLET_NEW_GENERATION_ERROR',
  WALLET_NEW_GENERATION_FINISH: 'WALLET_NEW_GENERATION_FINISH',

  WALLET_NEW_ACTIVATION: 'WALLET_NEW_ACTIVATION',
  WALLET_NEW_ACTIVATION_START: 'WALLET_NEW_ACTIVATION_START',
  WALLET_NEW_ACTIVATION_SUCCESS: 'WALLET_NEW_ACTIVATION_SUCCESS',
  WALLET_NEW_ACTIVATION_ERROR: 'WALLET_NEW_ACTIVATION_ERROR',
  WALLET_NEW_ACTIVATION_FINISH: 'WALLET_NEW_ACTIVATION_FINISH',

  // import
  WALLET_IMPORT: 'WALLET_IMPORT',
  WALLET_IMPORT_RESULT: 'WALLET_IMPORT_RESULT',

  WALLET_CHECK_IMPORTED: 'WALLET_CHECK_IMPORTED',
  WALLET_CHECK_IMPORTED_START: 'WALLET_IMPORT_START',
  WALLET_CHECK_IMPORTED_SUCCESS: 'WALLET_IMPORT_SUCCESS',
  WALLET_CHECK_IMPORTED_ERROR: 'WALLET_IMPORT_ERROR',
  WALLET_CHECK_IMPORTED_FINISH: 'WALLET_IMPORT_FINISH',
}
